name: Tests

on: pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage ./lib
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v2
        with:
          coverage-files: coverage/lcov*.info
          minimum-coverage: 80
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
